services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-network

  tech-challenge-api:
    build: .
    container_name: tech-challenge-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgres
    networks:
      - postgres-network

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
      - postgres-network
  
  payment:
    image: 'guedeslucas/lg-tech-challenge-payment:latest'
    environment:
      - SERVER_PORT=8081
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=tech_payment
      - DB_USER=techchallenge
      - DB_PASSWORD=123456
      - WEBHOOK_URL=http://localhost:8080
      - WEBHOOK_PATH=/pagamento/webhook/
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - pgadmin
    network_mode: "host"
    
networks:
  postgres-network:
    driver: bridge
  
